import express from 'express';
import http from 'node:http';
import {Server} from 'socket.io';
import {randomInt,randomUUID} from 'node:crypto';
const app=express(),server=http.createServer(app),io=new Server(server),PORT=process.env.PORT||3000,rooms=new Map();
const colors=['#ff4757','#2ed573','#1e90ff','#ffa502','#a55eea','#00d2d3','#ff6b81','#eccc68'],avatars=['😎','🤓','🥳','🤠','😜','😁','😮','😏'];
const games=['Quiz Battle','Färgfeed','Bomben','Mini-race','Copycat','Rött ljus / grönt ljus','Prickskytten','Stoppa på 10.00','Chicken','Växla!','Hal is','Hajen kommer','Väggen','Kanonduell','Helikoptern','Radiobilsfotboll'];
const info={
'Quiz Battle':{icon:'🧠',hint:'Välj rätt svar så snabbt du kan.'},'Färgfeed':{icon:'🎨',hint:'Tryck rätt färg blixtsnabbt.'},'Bomben':{icon:'💣',hint:'Tryck så nära den hemliga tiden du vågar.'},'Mini-race':{icon:'🏎️',hint:'Tappa snabbt för att köra mot mål.'},'Copycat':{icon:'🧩',hint:'Kom ihåg och upprepa pilsekvensen.'},'Rött ljus / grönt ljus':{icon:'🚦',hint:'Rör dig på grönt. Stanna på rött.'},'Prickskytten':{icon:'🎯',hint:'Skjut när siktet är mitt i prick.'},'Stoppa på 10.00':{icon:'⏱️',hint:'Stoppa så nära exakt 10.000 sekunder du kan.'},'Chicken':{icon:'🐔',hint:'Bromsa så sent som möjligt utan att krascha.'},'Växla!':{icon:'⚙️',hint:'Växla när varvräknaren träffar grönt.'},'Hal is':{icon:'🧊',hint:'Styr vänster/höger och håll balansen.'},'Hajen kommer':{icon:'🦈',hint:'Simma snabbt men bränn inte all stamina.'},'Väggen':{icon:'🧱',hint:'Välj rätt öppning innan väggen träffar.'},'Kanonduell':{icon:'💥',hint:'Avfyra när kanonen har perfekt vinkel.'},'Helikoptern':{icon:'🚁',hint:'Håll för upp, släpp för ner.'},'Radiobilsfotboll':{icon:'⚽',hint:'Styr, boosta och gör mål. Tre insläppta = ute.'}};
app.use(express.static('public'));app.get('/health',(_,r)=>r.json({ok:true,rooms:rooms.size,version:'0.2.11'}));
function code(){const c='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let v='';do{v=Array.from({length:5},()=>c[randomInt(c.length)]).join('')}while(rooms.has(v));return v}const player=(r,id)=>r.players.find(p=>p.id===id),socketPlayer=(r,s)=>player(r,s.data.playerId);const cleanTimers=r=>{if(r.game?.timers)r.game.timers.forEach(clearTimeout)};
function pub(r){const g=r.game;return{code:r.code,phase:r.phase,hostConnected:Boolean(r.hostId),players:r.players.map(p=>({id:p.id,name:p.name,color:p.color,avatar:p.avatar,score:p.score,voted:p.voted,ready:p.ready,connected:p.connected!==false,done:Boolean(g?.done?.has(p.id)),roundScore:g?.scores?.get(p.id)||0})),chat:r.chat||[],voteOptions:r.voteOptions,gameOptions:games.map(name=>({name,playable:true,icon:info[name].icon})),selectedGame:r.selectedGame,game:g?{name:g.name,status:g.status,startsAt:g.startsAt,endsAt:g.endsAt,revealUntil:g.revealUntil,prompt:g.prompt,options:g.options,signal:g.signal,progress:Object.fromEntries(g.progress||[]),results:g.results||[],hint:info[g.name]?.hint,icon:info[g.name]?.icon}:null}}
function emit(r){io.to(r.code).emit('room:update',pub(r))}function baseGame(name,status='practice'){return{name,status,startsAt:Date.now(),endsAt:0,revealUntil:0,done:new Set(),scores:new Map(),progress:new Map(),actions:new Map(),timers:[],results:[]}}
function practice(r,name){cleanTimers(r);r.selectedGame=name;r.phase='practice';r.players.forEach(p=>p.ready=false);r.game=baseGame(name);r.game.prompt=info[name].hint;emit(r)}
function finish(r){const g=r.game;if(!g||g.status==='results')return;cleanTimers(r);const results=r.players.map(p=>{const points=Math.max(0,Math.round(g.scores.get(p.id)||0));p.score+=points;return{id:p.id,name:p.name,color:p.color,avatar:p.avatar,points,total:p.score}}).sort((a,b)=>b.points-a.points);g.status='results';g.results=results;r.phase='results';emit(r)}
function start(r){const g=baseGame(r.selectedGame,'countdown'),now=Date.now();r.game=g;r.phase='game';r.players.forEach(p=>p.ready=false);g.startsAt=now+3000;let duration=12000;const name=g.name;
if(name==='Stoppa på 10.00'){duration=15000;g.revealUntil=g.startsAt+2000;g.prompt='Stoppa på exakt 10.000';}
else if(name==='Quiz Battle'){duration=9000;const a=randomInt(3,15),b=randomInt(2,12),correct=a+b,opts=[correct,correct+randomInt(1,5),Math.max(0,correct-randomInt(1,5)),correct+randomInt(5,9)].sort(()=>Math.random()-.5);g.prompt=`${a} + ${b} = ?`;g.options=opts.map(String);g.correct=String(correct)}
else if(name==='Färgfeed'){duration=8000;const cs=['RÖD','BLÅ','GRÖN','GUL'];g.correct=cs[randomInt(cs.length)];g.prompt=`TRYCK ${g.correct}`;g.options=cs}
else if(['Bomben','Prickskytten','Chicken','Kanonduell'].includes(name)){duration=10000;g.target={Bomben:6500,Prickskytten:5000,Chicken:7800,Kanonduell:4500}[name];g.prompt=name==='Chicken'?'BROMSA innan väggen!':name==='Bomben'?'Vänta… och TRYCK!':name==='Prickskytten'?'Skjut mitt i prick!':'Avfyra i perfekt vinkel!'}
else if(name==='Copycat'){duration=15000;const arrows=['⬆️','➡️','⬇️','⬅️'];g.sequence=Array.from({length:5},()=>arrows[randomInt(4)]);g.prompt=g.sequence.join(' ');g.options=arrows;g.revealUntil=g.startsAt+3500}
else if(name==='Rött ljus / grönt ljus'){duration=14000;g.signal='GRÖNT';for(let t=2500;t<duration;t+=2500){g.timers.push(setTimeout(()=>{if(r.game===g){g.signal=g.signal==='GRÖNT'?'RÖTT':'GRÖNT';emit(r)}},3000+t))}}
else if(name==='Växla!'){duration=13000;g.prompt='Växla 5 gånger vid rätt ögonblick!';g.targets=[2000,4000,6000,8000,10000]}
else if(name==='Väggen'){duration=13000;g.correct=String(randomInt(1,4));g.options=['1','2','3'];g.prompt=`ÖPPNING ${g.correct}`}
else if(name==='Hal is'){duration=12000;g.options=['VÄNSTER','HÖGER'];g.prompt='Håll bilen i balans!'}
else if(name==='Hajen kommer'){duration=12000;g.prompt='SIMMA! Lagom snabbt ger mest stamina.'}
else if(name==='Helikoptern'){duration=12000;g.prompt='Håll UPPE, släpp NERE genom tunneln.'}
else if(name==='Radiobilsfotboll'){duration=15000;g.options=['VÄNSTER','BOOST','HÖGER'];g.prompt='Styr och boosta mot bollen!'}
else if(name==='Mini-race'){duration=12000;g.prompt='TAPPA för att köra!'}
g.endsAt=g.startsAt+duration;emit(r);g.timers.push(setTimeout(()=>{if(r.game===g){g.status='running';emit(r)}},3000));g.timers.push(setTimeout(()=>{if(r.game===g)finish(r)},3000+duration+250))}
function scoreAction(r,p,data={}){const g=r.game;if(!g||r.phase!=='game'||Date.now()<g.startsAt||Date.now()>g.endsAt||g.done.has(p.id))return;const elapsed=Date.now()-g.startsAt,name=g.name,action=String(data.action||'');let sc=g.scores.get(p.id)||0,acts=g.actions.get(p.id)||[];
if(name==='Stoppa på 10.00'){sc=Math.max(0,1000-Math.abs(elapsed-10000)*.2);g.done.add(p.id)}
else if(name==='Quiz Battle'||name==='Färgfeed'||name==='Väggen'){sc=action===g.correct?Math.max(200,1000-elapsed*.07):0;g.done.add(p.id)}
else if(['Bomben','Prickskytten','Chicken','Kanonduell'].includes(name)){const diff=Math.abs(elapsed-g.target);sc=Math.max(0,1000-diff*.25);if(name==='Chicken'&&elapsed>g.target+700)sc=0;g.done.add(p.id)}
else if(name==='Copycat'){acts.push(action);g.actions.set(p.id,acts);const i=acts.length-1;if(action!==g.sequence[i]){sc=Math.max(0,sc-150)}else sc+=200;if(acts.length>=g.sequence.length)g.done.add(p.id)}
else if(name==='Mini-race'){sc=Math.min(1000,sc+35);g.progress.set(p.id,Math.min(100,sc/10))}
else if(name==='Rött ljus / grönt ljus'){sc+=g.signal==='GRÖNT'?55:-120;sc=Math.max(0,sc);g.progress.set(p.id,Math.min(100,sc/10));if(sc>=1000)g.done.add(p.id)}
else if(name==='Växla!'){const i=acts.length;if(i<5){const diff=Math.abs(elapsed-g.targets[i]);sc+=Math.max(0,200-diff*.15);acts.push(elapsed);g.actions.set(p.id,acts);if(acts.length===5)g.done.add(p.id)}}
else if(name==='Hal is'){const last=acts.at(-1);sc+=last&&last===action?15:55;acts.push(action);g.actions.set(p.id,acts);g.progress.set(p.id,Math.min(100,sc/10))}
else if(name==='Hajen kommer'){const last=acts.at(-1)||-1000,gap=elapsed-last;sc+=gap<120?5:gap<450?45:25;acts.push(elapsed);g.actions.set(p.id,acts);g.progress.set(p.id,Math.min(100,sc/10))}
else if(name==='Helikoptern'){sc+=action==='UP'?45:30;g.progress.set(p.id,Math.min(100,sc/10))}
else if(name==='Radiobilsfotboll'){sc+=action==='BOOST'?50:30;g.progress.set(p.id,Math.min(100,sc/10))}
g.scores.set(p.id,Math.min(1000,sc));emit(r);if(g.done.size===r.players.length)finish(r)}
function vote(r){cleanTimers(r);r.phase='voting';r.game=null;r.selectedGame=null;r.votes.clear();r.players.forEach(p=>{p.voted=false;p.ready=false});r.voteOptions=[...games].sort(()=>Math.random()-.5).slice(0,3);emit(r)}
io.on('connection',s=>{s.on('time:sync',(_,cb=()=>{})=>cb({serverNow:Date.now()}));
s.on('host:create',(_,cb=()=>{})=>{const c=code(),hostToken=randomUUID(),r={code:c,hostId:s.id,hostToken,phase:'lobby',players:[],chat:[],voteOptions:[],votes:new Map(),selectedGame:null,game:null};rooms.set(c,r);s.join(c);s.data.roomCode=c;s.data.role='host';s.data.hostToken=hostToken;cb({ok:true,sessionToken:hostToken,room:pub(r)});emit(r)});
s.on('player:join',({roomCode,name,avatar},cb=()=>{})=>{const r=rooms.get(String(roomCode||'').trim().toUpperCase());if(!r)return cb({ok:false,error:'Lobbyn finns inte.'});if(r.players.length>=8)return cb({ok:false,error:'Lobbyn är full.'});if(!['lobby','voting','selected','choosing'].includes(r.phase))return cb({ok:false,error:'En runda pågår.'});const id=randomUUID(),p={id,name:String(name||'Spelare').trim().slice(0,18)||'Spelare',color:colors[r.players.length%8],avatar:avatars[Math.max(0,Math.min(7,parseInt(avatar)||0))],score:0,voted:false,ready:false,connected:true,socketId:s.id};r.players.push(p);s.join(r.code);s.data.roomCode=r.code;s.data.role='player';s.data.playerId=p.id;cb({ok:true,sessionToken:p.id,player:{id:p.id,name:p.name,color:p.color,avatar:p.avatar},room:pub(r)});emit(r)});
s.on('session:resume',({roomCode,role,sessionToken},cb=()=>{})=>{const r=rooms.get(String(roomCode||'').trim().toUpperCase()),token=String(sessionToken||'');if(!r)return cb({ok:false,error:'Matchen finns inte längre.'});if(role==='host'){if(token!==r.hostToken)return cb({ok:false,error:'Ogiltig värdsession.'});r.hostId=s.id;s.join(r.code);s.data.roomCode=r.code;s.data.role='host';s.data.hostToken=token;cb({ok:true,role:'host',room:pub(r)});emit(r);return}const p=player(r,token);if(!p)return cb({ok:false,error:'Spelaren finns inte längre.'});p.connected=true;p.socketId=s.id;s.join(r.code);s.data.roomCode=r.code;s.data.role='player';s.data.playerId=p.id;cb({ok:true,role:'player',player:{id:p.id,name:p.name,color:p.color,avatar:p.avatar},room:pub(r)});emit(r)});
s.on('chat:send',({text},cb=()=>{})=>{const r=rooms.get(s.data.roomCode),p=r&&socketPlayer(r,s);if(!r||!p||!['lobby','results'].includes(r.phase))return cb({ok:false});const t=String(text||'').trim().slice(0,160);if(!t)return cb({ok:false});r.chat.push({name:p.name,avatar:p.avatar,color:p.color,text:t,at:Date.now()});r.chat=r.chat.slice(-40);emit(r);cb({ok:true})});s.on('player:lobbyReady',(_,cb=()=>{})=>{const r=rooms.get(s.data.roomCode),p=r&&socketPlayer(r,s);if(!r||!p||r.phase!=='lobby')return cb({ok:false});p.ready=!p.ready;emit(r);cb({ok:true})});
s.on('host:startVote',(_,cb=()=>{})=>{const r=rooms.get(s.data.roomCode);if(!r||r.hostId!==s.id||!r.players.length)return cb({ok:false});vote(r);cb({ok:true})});s.on('host:nextGame',(_,cb=()=>{})=>{const r=rooms.get(s.data.roomCode);if(!r||r.hostId!==s.id||r.phase!=='results')return cb({ok:false});vote(r);cb({ok:true})});s.on('host:startChoose',(_,cb=()=>{})=>{const r=rooms.get(s.data.roomCode);if(!r||r.hostId!==s.id||!r.players.length)return cb({ok:false});cleanTimers(r);r.phase='choosing';r.game=null;r.selectedGame=null;emit(r);cb({ok:true})});s.on('host:chooseGame',({game},cb=()=>{})=>{const r=rooms.get(s.data.roomCode);if(!r||r.hostId!==s.id||!games.includes(game))return cb({ok:false});r.selectedGame=game;r.phase='selected';emit(r);cb({ok:true})});
s.on('player:vote',({game},cb=()=>{})=>{const r=rooms.get(s.data.roomCode),p=r&&socketPlayer(r,s);if(!r||!p||r.phase!=='voting'||!r.voteOptions.includes(game))return cb({ok:false});r.votes.set(p.id,game);p.voted=true;emit(r);cb({ok:true});if(r.votes.size===r.players.length){const count=Object.fromEntries(r.voteOptions.map(x=>[x,0]));for(const x of r.votes.values())count[x]++;const m=Math.max(...Object.values(count)),t=r.voteOptions.filter(x=>count[x]===m);r.selectedGame=t[randomInt(t.length)];r.phase='selected';emit(r)}});s.on('host:startSelected',(_,cb=()=>{})=>{const r=rooms.get(s.data.roomCode);if(!r||r.hostId!==s.id||!r.selectedGame)return cb({ok:false});practice(r,r.selectedGame);cb({ok:true})});s.on('host:startTen',(_,cb=()=>{})=>{const r=rooms.get(s.data.roomCode);if(!r||r.hostId!==s.id||!r.players.length)return cb({ok:false});practice(r,'Stoppa på 10.00');cb({ok:true})});
s.on('player:ready',(_,cb=()=>{})=>{const r=rooms.get(s.data.roomCode),p=r&&socketPlayer(r,s);if(!r||!p||r.phase!=='practice')return cb({ok:false});p.ready=true;emit(r);cb({ok:true});if(r.players.length&&r.players.every(x=>x.ready))start(r)});s.on('game:action',(data,cb=()=>{})=>{const r=rooms.get(s.data.roomCode),p=r&&socketPlayer(r,s);if(!r||!p)return cb({ok:false});scoreAction(r,p,data);cb({ok:true})});s.on('player:stopTen',(_,cb=()=>{})=>{const r=rooms.get(s.data.roomCode),p=r&&socketPlayer(r,s);if(!r||!p)return cb({ok:false});scoreAction(r,p,{action:'STOP'});cb({ok:true})});
s.on('player:leave',(_,cb=()=>{})=>{const r=rooms.get(s.data.roomCode),p=r&&socketPlayer(r,s);if(!r||!p)return cb({ok:false});if(!['lobby','voting','selected','choosing','results'].includes(r.phase))return cb({ok:false,error:'Du kan inte lämna mitt under en omgång.'});r.votes.delete(p.id);r.players=r.players.filter(x=>x.id!==p.id);s.leave(r.code);s.data.playerId=null;s.data.roomCode=null;s.data.role=null;emit(r);cb({ok:true})});
s.on('host:removePlayer',({playerId},cb=()=>{})=>{const r=rooms.get(s.data.roomCode);if(!r||r.hostId!==s.id)return cb({ok:false});if(!['lobby','voting','selected','choosing','results'].includes(r.phase))return cb({ok:false,error:'Kan inte ta bort spelare mitt under en omgång.'});const p=player(r,String(playerId||''));if(!p)return cb({ok:false});r.votes.delete(p.id);if(p.socketId)io.to(p.socketId).emit('player:removed');r.players=r.players.filter(x=>x.id!==p.id);emit(r);cb({ok:true})});
s.on('host:exit',(_,cb=()=>{})=>{const r=rooms.get(s.data.roomCode);if(!r||r.hostId!==s.id)return cb({ok:false});cleanTimers(r);io.to(r.code).emit('room:ended');rooms.delete(r.code);cb({ok:true})});
s.on('disconnect',()=>{const r=rooms.get(s.data.roomCode);if(!r)return;if(s.data.role==='host'&&r.hostId===s.id){r.hostId=null;emit(r);return}const p=socketPlayer(r,s);if(p&&p.socketId===s.id){p.connected=false;emit(r)}})});server.listen(PORT,'0.0.0.0',()=>console.log(`Partybox v0.2.11 running on :${PORT}`));